import type { Car } from "./types";

// Stock real de Prestige Motors (Planilla Junio 2026).
// Fallback en memoria cuando Supabase no está configurado.
// Fotos: placeholders locales con la marca (public/placeholders).
// Reemplazar por fotos reales de cada unidad para producción.

export const SEED_CARS: Car[] = [
  {
    id: "1",
    brand: "Toyota",
    model: "Hilux",
    version: "4X4 D/C LIMITED 2.8 TDI 6 MT",
    year: 2018,
    km: 167051,
    price: 39999000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Diésel",
    category: "Pick-up",
    color: "Bordó",
    image_url: "/placeholders/pickup.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-07-20T12:00:00Z",
  },
  {
    id: "2",
    brand: "Toyota",
    model: "Hilux",
    version: "4X4 CD SRX 2.8 177 CV AT",
    year: 2026,
    km: 0,
    price: 85000000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Diésel",
    category: "Pick-up",
    color: "Negra",
    image_url: "/placeholders/pickup.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-07-19T12:00:00Z",
  },
  {
    id: "3",
    brand: "Toyota",
    model: "Yaris",
    version: "CROSS SEG CVT 1.5",
    year: 2026,
    km: 0,
    price: 53999000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Nafta",
    category: "SUV",
    color: "Azul",
    image_url: "/placeholders/suv.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-07-18T12:00:00Z",
  },
  {
    id: "4",
    brand: "Toyota",
    model: "Etios",
    version: "XLS 1.5 4P AT COLA LARGA",
    year: 2019,
    km: 119913,
    price: 23500000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Nafta",
    category: "Sedán",
    color: "Blanco",
    image_url: "/placeholders/sedan.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-17T12:00:00Z",
  },
  {
    id: "5",
    brand: "Toyota",
    model: "Etios",
    version: "XLS 1.5 AT COLA LARGA",
    year: 2019,
    km: 46610,
    price: 23999000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Nafta",
    category: "Sedán",
    color: "Champage",
    image_url: "/placeholders/sedan.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-16T12:00:00Z",
  },
  {
    id: "6",
    brand: "Toyota",
    model: "Corolla",
    version: "SEG CVT",
    year: 2013,
    km: 177000,
    price: 16999000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Nafta",
    category: "Sedán",
    color: "Blanco",
    image_url: "/placeholders/sedan.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-15T12:00:00Z",
  },
  {
    id: "7",
    brand: "Toyota",
    model: "Corolla",
    version: "XEI MT",
    year: 2019,
    km: 70000,
    price: 26999000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Sedán",
    color: "Gris plata",
    image_url: "/placeholders/sedan.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-14T12:00:00Z",
  },
  {
    id: "8",
    brand: "Toyota",
    model: "Corolla",
    version: "XEI CVT 2.0",
    year: 2022,
    km: 83500,
    price: 36499000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Nafta",
    category: "Sedán",
    color: "Gris plata",
    image_url: "/placeholders/sedan.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-13T12:00:00Z",
  },
  {
    id: "9",
    brand: "Toyota",
    model: "Corolla",
    version: "CROSS GR-SPORT 2.0 CVT",
    year: 2023,
    km: 47854,
    price: 48999000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Nafta",
    category: "SUV",
    color: "Blanco",
    image_url: "/placeholders/suv.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-12T12:00:00Z",
  },
  {
    id: "10",
    brand: "Toyota",
    model: "RAV4",
    version: "VX 4X2 AT",
    year: 2018,
    km: 103607,
    price: 38499000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Nafta",
    category: "SUV",
    color: "Blanca",
    image_url: "/placeholders/suv.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-11T12:00:00Z",
  },
  {
    id: "11",
    brand: "Toyota",
    model: "SW4",
    version: "GR- SPORT AT",
    year: 2024,
    km: 30700,
    price: 89999000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Nafta",
    category: "SUV",
    color: "Blanca y negro",
    image_url: "/placeholders/suv.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-07-10T12:00:00Z",
  },
  {
    id: "12",
    brand: "Toyota",
    model: "Yaris",
    version: "XLS PACK CVT",
    year: 2024,
    km: 27000,
    price: 31999000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Nafta",
    category: "Hatchback",
    color: "Gris oscuro",
    image_url: "/placeholders/hatchback.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-09T12:00:00Z",
  },
  {
    id: "13",
    brand: "BMW",
    model: "X4",
    version: "28I XDRIVE 2.8",
    year: 2018,
    km: 58390,
    price: 47000,
    currency: "USD",
    transmission: "Automático",
    fuel: "Nafta",
    category: "SUV",
    color: "Negra",
    image_url: "/placeholders/suv.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-07-08T12:00:00Z",
  },
  {
    id: "14",
    brand: "Citroën",
    model: "C",
    version: "C-ELYSEE VTI LIVE",
    year: 2018,
    km: 110234,
    price: 14499000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Sedán",
    color: "Gris",
    image_url: "/placeholders/sedan.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-07T12:00:00Z",
  },
  {
    id: "15",
    brand: "Fiat",
    model: "Palio",
    version: "FIRE COMUN 1.4",
    year: 2015,
    km: 161000,
    price: 12999000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Hatchback",
    color: "Blanco",
    image_url: "/placeholders/hatchback.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-06T12:00:00Z",
  },
  {
    id: "16",
    brand: "Fiat",
    model: "Mobi",
    version: "TREKKING 1.0",
    year: 2026,
    km: 0,
    price: 29499000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Hatchback",
    color: "Gris",
    image_url: "/placeholders/hatchback.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-07-05T12:00:00Z",
  },
  {
    id: "17",
    brand: "Fiat",
    model: "Titano",
    version: "FREEDOM 4X4 AT PLUS AWD 2.2",
    year: 2025,
    km: 2560,
    price: 53999000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Diésel",
    category: "Pick-up",
    color: "Blanca",
    image_url: "/placeholders/pickup.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-07-04T12:00:00Z",
  },
  {
    id: "18",
    brand: "Ford",
    model: "Ecosport",
    version: "TITANIUM 1.6 MT",
    year: 2013,
    km: 177260,
    price: 12999000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "SUV",
    color: "Gris plata",
    image_url: "/placeholders/suv.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-03T12:00:00Z",
  },
  {
    id: "19",
    brand: "Ford",
    model: "Ecosport",
    version: "XLS MT 4X2",
    year: 2010,
    km: 161384,
    price: 10499000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "SUV",
    color: "Gris plata",
    image_url: "/placeholders/suv.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-02T12:00:00Z",
  },
  {
    id: "20",
    brand: "Ford",
    model: "Ecosport",
    version: "SE 1.6L",
    year: 2017,
    km: 60000,
    price: 15500000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "SUV",
    color: "Negra",
    image_url: "/placeholders/suv.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-07-01T12:00:00Z",
  },
  {
    id: "21",
    brand: "Ford",
    model: "Mondeo",
    version: "ECOBOOST",
    year: 2018,
    km: 122292,
    price: 29999000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Nafta",
    category: "Sedán",
    color: "Blanco",
    image_url: "/placeholders/sedan.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-30T12:00:00Z",
  },
  {
    id: "22",
    brand: "Jeep",
    model: "Compass",
    version: "LIMITED AT",
    year: 2013,
    km: 159000,
    price: 17999000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Nafta",
    category: "SUV",
    color: "Blanca",
    image_url: "/placeholders/suv.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-29T12:00:00Z",
  },
  {
    id: "23",
    brand: "Mercedes Benz",
    model: "A200",
    version: "PROGRESIVE",
    year: 2021,
    km: 61000,
    price: 39999,
    currency: "USD",
    transmission: "Automático",
    fuel: "Nafta",
    category: "Sedán",
    color: "Gris",
    image_url: "/placeholders/sedan.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-06-28T12:00:00Z",
  },
  {
    id: "24",
    brand: "Mercedes Benz",
    model: "ML",
    version: "350 BLUE EFFICIENCY",
    year: 2013,
    km: 151900,
    price: 27500,
    currency: "USD",
    transmission: "Automático",
    fuel: "Diésel",
    category: "SUV",
    color: "Blanca",
    image_url: "/placeholders/suv.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-27T12:00:00Z",
  },
  {
    id: "25",
    brand: "Nissan",
    model: "New Kicks",
    version: "EXCLUSIVE 1.0T DCT",
    year: 2026,
    km: 0,
    price: 61999000,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Nafta",
    category: "SUV",
    color: "Blanco",
    image_url: "/placeholders/suv.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-06-26T12:00:00Z",
  },
  {
    id: "26",
    brand: "Peugeot",
    model: "Partner",
    version: "FURGON CONFORT 1.6",
    year: 2023,
    km: 14500,
    price: 25999000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Utilitario",
    color: "Blanca",
    image_url: "/placeholders/utilitario.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-25T12:00:00Z",
  },
  {
    id: "27",
    brand: "Peugeot",
    model: "208",
    version: "GT LINE 1.2",
    year: 2021,
    km: 67000,
    price: 29000000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Hatchback",
    color: "Amarillo",
    image_url: "/placeholders/hatchback.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-24T12:00:00Z",
  },
  {
    id: "28",
    brand: "Renault",
    model: "Duster",
    version: "PH2 PRIVILEGE 1.6",
    year: 2015,
    km: 0,
    price: 17499000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "SUV",
    color: "Verde oliva",
    image_url: "/placeholders/suv.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-23T12:00:00Z",
  },
  {
    id: "29",
    brand: "Renault",
    model: "Duster",
    version: "PRIVILEGE 2.0",
    year: 2017,
    km: 149837,
    price: null,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "SUV",
    color: "Gris plata",
    image_url: "/placeholders/suv.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-22T12:00:00Z",
  },
  {
    id: "30",
    brand: "Renault",
    model: "Duster",
    version: "EXPRESS 4X2 1.6",
    year: 2020,
    km: 32890,
    price: 23499000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "SUV",
    color: "Gris oscuro",
    image_url: "/placeholders/suv.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-21T12:00:00Z",
  },
  {
    id: "31",
    brand: "Renault",
    model: "Fluence",
    version: "LUXE PACK",
    year: 2015,
    km: 143458,
    price: 13999000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Sedán",
    color: "Negro",
    image_url: "/placeholders/sedan.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-20T12:00:00Z",
  },
  {
    id: "32",
    brand: "Renault",
    model: "Kwid",
    version: "ICONIC 1.0 MT BITONO",
    year: 2026,
    km: 0,
    price: 25899000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Hatchback",
    color: "Gris oscuro",
    image_url: "/placeholders/hatchback.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-06-19T12:00:00Z",
  },
  {
    id: "33",
    brand: "Renault",
    model: "Logan",
    version: "LIFE 1.6 MT",
    year: 2026,
    km: 0,
    price: 31000000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Sedán",
    color: "Blanco",
    image_url: "/placeholders/sedan.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-06-18T12:00:00Z",
  },
  {
    id: "34",
    brand: "Renault",
    model: "Kangoo II",
    version: "EXPRESS CONFORT 1.6",
    year: 2022,
    km: 39000,
    price: 24999000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Utilitario",
    color: "Blanco",
    image_url: "/placeholders/utilitario.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-17T12:00:00Z",
  },
  {
    id: "35",
    brand: "Renault",
    model: "Kangoo II",
    version: "EXPRESS II 5A 1.6 SCE114 mt",
    year: 2026,
    km: 0,
    price: 41000000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Utilitario",
    color: "Blanco",
    image_url: "/placeholders/utilitario.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-06-16T12:00:00Z",
  },
  {
    id: "36",
    brand: "Chevrolet",
    model: "Onix",
    version: "1.0 T LT MT",
    year: 2025,
    km: 2781,
    price: 28499000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Hatchback",
    color: "Blanco",
    image_url: "/placeholders/hatchback.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-15T12:00:00Z",
  },
  {
    id: "37",
    brand: "Volkswagen",
    model: "Amarok",
    version: "V6 EXTREME",
    year: 2023,
    km: 51000,
    price: null,
    currency: "ARS",
    transmission: "Automático",
    fuel: "Diésel",
    category: "Pick-up",
    color: "Gris plata",
    image_url: "/placeholders/pickup.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-06-14T12:00:00Z",
  },
  {
    id: "38",
    brand: "Volkswagen",
    model: "The Beetle",
    version: "1.4 MT TSI DESIGN MQ",
    year: 2015,
    km: 165400,
    price: 19999000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Hatchback",
    color: "Blanco",
    image_url: "/placeholders/hatchback.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-13T12:00:00Z",
  },
  {
    id: "39",
    brand: "Volkswagen",
    model: "Suran",
    version: "HIGHLINE MT 1.6",
    year: 2018,
    km: 133200,
    price: 17999000,
    currency: "ARS",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Hatchback",
    color: "Rojo",
    image_url: "/placeholders/hatchback.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-12T12:00:00Z",
  },
  {
    id: "40",
    brand: "Volkswagen",
    model: "Delivery",
    version: "9-180",
    year: 2026,
    km: 0,
    price: 59000,
    currency: "USD",
    transmission: "Automático",
    fuel: "Diésel",
    category: "Camión",
    color: "Blanco",
    image_url: "/placeholders/camion.jpg",
    featured: true,
    status: "disponible",
    created_at: "2026-06-11T12:00:00Z",
  },
  {
    id: "41",
    brand: "Honda",
    model: "Crossrunner",
    version: "800CC",
    year: 2011,
    km: 29000,
    price: 15000,
    currency: "USD",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Moto",
    color: "Blanca",
    image_url: "/placeholders/moto.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-10T12:00:00Z",
  },
  {
    id: "42",
    brand: "BMW",
    model: "S1000",
    version: "XR",
    year: 2017,
    km: 16000,
    price: 21999,
    currency: "USD",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Moto",
    color: "Roja",
    image_url: "/placeholders/moto.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-09T12:00:00Z",
  },
  {
    id: "43",
    brand: "Sea Doo",
    model: "RXT ISS",
    version: "255 CV",
    year: 2009,
    km: 0,
    price: 18500,
    currency: "USD",
    transmission: "Manual",
    fuel: "Nafta",
    category: "Náutica",
    color: "Amarilla",
    image_url: "/placeholders/nautica.jpg",
    featured: false,
    status: "disponible",
    created_at: "2026-06-08T12:00:00Z",
  },
];
